/* Dropeamos todas las tablas existentes para evitar duplicidades y confusiones */

DROP TABLE CONVENIOS CASCADE CONSTRAINTS;
DROP TABLE PROPIEDADES CASCADE CONSTRAINTS;
DROP TABLE INMOBILIARIAS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;

/* Creacion de Tablas y sus respectivos atributos, PK y FK */

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER(10) PRIMARY KEY,
    APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    ESTADO_CIVIL VARCHAR2(20) NOT NULL,
    RENTA NUMBER(10,0) NOT NULL
);

CREATE TABLE PROPIEDADES (
    ID_PROPIEDAD NUMBER(10) PRIMARY KEY,
    DIRECCION VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(30) NOT NULL,
    PRECIO_ARRIENDO NUMBER(10,0) NOT NULL,
    ID_CLIENTE NUMBER(10) NOT NULL,

    CONSTRAINT FK_PROPIEDADES_CLIENTES
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE INMOBILIARIAS (
    ID_INMOBILIARIA NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CONTACTO VARCHAR2(100) NOT NULL
);

CREATE TABLE CONVENIOS (
    ID_CONVENIO NUMBER(10) PRIMARY KEY,
    ID_INMOBILIARIA NUMBER(10) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,

    CONSTRAINT FK_CONVENIOS_INMOBILIARIAS
        FOREIGN KEY (ID_INMOBILIARIA)
        REFERENCES INMOBILIARIAS(ID_INMOBILIARIA)
);


/* Inserccion de Datos para "CLIENTES" */

INSERT INTO CLIENTES VALUES (1, 'Garcia', 'Juan', 'Soltero', 750000);
INSERT INTO CLIENTES VALUES (2, 'Lopez', 'Ana', 'Divorciada', 850000);
INSERT INTO CLIENTES VALUES (3, 'Martinez', 'Pedro', 'Separado', 900000);
INSERT INTO CLIENTES VALUES (4, 'Rodriguez', 'Luis', 'Soltero', 600000);
INSERT INTO CLIENTES VALUES (5, 'Sanchez', 'Maria', 'Divorciada', 820000);

/* Inserccion de Datos para "PROPIEDADES" */

INSERT INTO PROPIEDADES VALUES (1, 'Av. Siempre Viva 742', 'Departamento', 500000, 1);
INSERT INTO PROPIEDADES VALUES (2, 'Calle Falsa 123', 'Loft', 600000, 2);
INSERT INTO PROPIEDADES VALUES (3, 'Av. Las Flores 321', 'Departamento', 700000, 3);
INSERT INTO PROPIEDADES VALUES (4, 'Pasaje Los Cedros 456', 'Loft', 400000, 4);
INSERT INTO PROPIEDADES VALUES (5, 'Calle La Paz 678', 'Departamento', 800000, 5);

/* Inserccion de Datos para "INMOBILIARIAS" */

INSERT INTO INMOBILIARIAS VALUES (1, 'UN SUEÑO', 'contacto@unsueno.com');
INSERT INTO INMOBILIARIAS VALUES (2, 'HOGAR IDEAL', 'contacto@hogarideal.com');

/* Inserccion de Datos para "CONVENIOS" */

INSERT INTO CONVENIOS VALUES (1, 1, TO_DATE('2025-01-01','YYYY-MM-DD'), TO_DATE('2027-01-01','YYYY-MM-DD'));
INSERT INTO CONVENIOS VALUES (2, 2, TO_DATE('2025-06-01','YYYY-MM-DD'), TO_DATE('2027-06-01','YYYY-MM-DD'));

COMMIT;

/* Consultas para CLIENTES y su respectivo ESTADO_CIVIL */

SELECT *
FROM CLIENTES
WHERE ESTADO_CIVIL IN ('Soltero', 'Separado', 'Divorciada')
ORDER BY APELLIDO_PATERNO, NOMBRE;

/* Consultas para CLIENTES separados o divorciados con renta >= 800000  */

SELECT *
FROM CLIENTES
WHERE ESTADO_CIVIL IN ('Separado', 'Divorciada')
AND RENTA >= 800000
ORDER BY APELLIDO_PATERNO, NOMBRE;

/* CREACION DE VISTA */

CREATE OR REPLACE VIEW VW_CLIENTES_MARKETING AS
SELECT
    ID_CLIENTE,
    APELLIDO_PATERNO,
    NOMBRE,
    ESTADO_CIVIL,
    RENTA
FROM CLIENTES
WHERE ESTADO_CIVIL IN ('Separado', 'Divorciada')
AND RENTA >= 800000;
/

/* VERIFICACION DE VISTA */

SELECT *
FROM VW_CLIENTES_MARKETING;

/* Consulta para PROPIEDADES con CLIENTE asociado */

SELECT
    P.ID_PROPIEDAD,
    P.DIRECCION,
    P.TIPO,
    P.PRECIO_ARRIENDO,
    C.ID_CLIENTE,
    C.NOMBRE,
    C.APELLIDO_PATERNO
FROM PROPIEDADES P
INNER JOIN CLIENTES C
ON P.ID_CLIENTE = C.ID_CLIENTE
ORDER BY P.TIPO, P.DIRECCION;

/* Consultar CONVENIOS vigentes con sus INMOBILIARIA */

SELECT
    CV.ID_CONVENIO,
    I.NOMBRE AS INMOBILIARIA,
    CV.FECHA_INICIO,
    CV.FECHA_FIN
FROM CONVENIOS CV
INNER JOIN INMOBILIARIAS I
ON CV.ID_INMOBILIARIA = I.ID_INMOBILIARIA
WHERE CV.FECHA_FIN >= SYSDATE;

/* Update de Ejemplo */

UPDATE CLIENTES
SET RENTA = 950000
WHERE ID_CLIENTE = 1;

SELECT *
FROM CLIENTES
WHERE ID_CLIENTE = 1;

/* Delete de Ejemplo */

DELETE FROM PROPIEDADES
WHERE ID_PROPIEDAD = 4;
ROLLBACK;

/* Mas ejemplos sobre SELECT */

SELECT
    NOMBRE,
    APELLIDO_PATERNO,
    RENTA
FROM CLIENTES
WHERE RENTA >= 800000;

SELECT
    COUNT(*) AS TOTAL_CLIENTES
FROM CLIENTES;

SELECT
    AVG(RENTA) AS PROMEDIO_RENTA
FROM CLIENTES;

SELECT
    MAX(PRECIO_ARRIENDO) AS ARRIENDO_MAS_ALTO
FROM PROPIEDADES;
